version: '3.2'
services:
 jenkins:
  image: vk85/vjenkins:1
  ports:
   - 8383:8080
   - 50000:50000
  container_name: vjenkins
  volumes:
   - /tmp/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
   - /var/run/docker.sock:/var/run/docker.sock
